### ISSUE TITLE
RSA Trusted Setup

### ISSUE THREAD

**Issue by burdges** [vdfresearch/vdfresearch.github.io#11]
There are seemingly no links for the RSA trusted setup MPCs being considered.  At least one MPC was published way back, right? Also, at least one newer MPC makes significant improvements, yes?  Add a quick section on RSA trusted setups maybe?

**Comment by JustinDrake** [comment]
There are various RSA MPC links on the page:

<img width="501" alt="Screenshot 2020-09-16 at 13 32 32" src="https://user-images.githubusercontent.com/731743/93337523-26fdd500-f821-11ea-9153-16fffb0cefe6.png">

<img width="505" alt="Screenshot 2020-09-16 at 13 32 17" src="https://user-images.githubusercontent.com/731743/93337512-249b7b00-f821-11ea-9ada-2a8db8d4d174.png">

**Comment by burdges** [comment]
I just missed them, thanks!
